### ISSUE TITLE
The frame is None.

### ISSUE THREAD

**Issue by JiangWeiHn** [CoskunGorkem/YOLOv5-Tracker#1]
When i run the main.py, i got this:
 ok, frame = cap.read() 
ok is false 
frame is None.

and then the programm runing at this line:
 blur_index = blur.variance_of_laplacian(frame)
got a error.
Why does this happen
My video format is avi

**Comment by CoskunGorkem** [comment]
Hello @JiangWeiHn,
`frame is None` means your video is not readable by the script, either the format or the video path might be the problem. Since the frame is None, laplacian of the frame is not calculated and you got this error. 
Could you share the command you used to run main.py? 

If you want to test whether the code works or not, you can see if it is running with `python main.py`, it will use the test video with default settings.

**Comment by JiangWeiHn** [comment]
I find the reason:
source_name = source.split("/")[-1]
I am runing the project in windows system. so the source_name is the full source ,and make the video null.
